spring:
  datasource:
    # config mysql
    url: jdbc:postgresql://192.168.44.131:8848/postgres
    username: gaussdb
    password: Enmo@123
    driver-class-name: org.postgresql.Driver
    #修改上传文件大小
  servlet:
    multipart:
      enabled: true
      # 单个文件大小
      max-file-size: 400MB
      #包含其他信息的整个请求大小
      max-request-size: 500MB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 关闭数据库下划线自动转驼峰
    map-underscore-to-camel-case: false
